export const default_blocks = {
    text: false,
    link: false,
    image: true,
    // LAYOUT
    container: true,
    row: true,
    column: true,
    column_break: true,
    media_object: true,
    // COMPONENTS
    alert: true,
    tabs: true,
    badge: true,
    button: false,
    button_group: true,
    button_toolbar: true,
    card: true,
    card_container: true,
    collapse: true,
    dropdown: true,
    video: true,
    // TYPOGRAPHY
    header: true,
    paragraph: true,
    // BASIC
    list: true,
    // FORMS
    form: false,
    input: false,
    form_group_input: false,
    input_group: false,
    textarea: false,
    select: false,
    label: false,
    checkbox: false,
    radio: false,
};

export const default_components = {
    default: false,
    text: false,
    link: false,
    image: true,
    // LAYOUT
    container: true,
    row: true,
    column: true,
    column_break: true,
    media_object: true,
    // COMPONENTS
    alert: true,
    tabs: true,
    badge: true,
    button: false,
    button_group: true,
    button_toolbar: true,
    card: true,
    card_container: true,
    collapse: true,
    dropdown: true,
    video: true,
    // TYPOGRAPHY
    header: true,
    paragraph: true,
    // BASIC
    list: true,
    // FORMS
    form: false,
    input: false,
    form_group_input: false,
    input_group: false,
    textarea: false,
    select: false,
    label: false,
    checkbox: false,
    radio: false,
};

export const default_block_categories = {
    text: 'Bootstrap Basic',
    link: 'Bootstrap Basic',
    image: 'Bootstrap Basic',
    // LAYOUT
    container: 'Bootstrap Layout',
    row: 'Bootstrap Layout',
    column: 'Bootstrap Layout',
    column_break: 'Bootstrap Layout',
    media_object: 'Bootstrap Layout',
    // COMPONENTS
    alert: 'Bootstrap Components',
    tabs: 'Bootstrap Components',
    badge: 'Bootstrap Components',
    button: 'Bootstrap Forms',
    button_group: 'Bootstrap Forms',
    button_toolbar: 'Bootstrap Forms',
    card: 'Bootstrap Components',
    card_container: 'Bootstrap Components',
    collapse: 'Bootstrap Components',
    dropdown: 'Bootstrap Components',
    video: 'Bootstrap Components',
    // TYPOGRAPHY
    header: 'Bootstrap Typography',
    paragraph: 'Bootstrap Typography',
    // BASIC
    list: 'Bootstrap Basic',
    // FORMS
    form: 'Bootstrap Forms',
    input: 'Bootstrap Forms',
    form_group_input: 'Bootstrap Forms',
    input_group: 'Bootstrap Forms',
    textarea: 'Bootstrap Forms',
    select: 'Bootstrap Forms',
    label: 'Bootstrap Forms',
    checkbox: 'Bootstrap Forms',
    radio: 'Bootstrap Forms',
}

export const default_labels = {
    // LAYOUT
    container: 'Container',
    row: 'Row',
    column: 'Column',
    column_break: 'Column Break',
    media_object: 'Media Object',

    // COMPONENTS
    alert: 'Alert',
    tabs: 'Tabs',
    tab: 'Tab',
    tabPane: 'Tab Pane',
    badge: 'Badge',
    button: 'Button',
    button_group: 'Button Group',
    button_toolbar: 'Button Toolbar',
    card: 'Card',
    card_container: 'Card Container',
    collapse: 'Collapse',
    dropdown: 'Dropdown',
    dropdown_menu: 'Dropdown Menu',
    dropdown_item: 'Dropdown Item',

    // MEDIA
    image: 'Image',
    video: 'Video',

    // TYPOGRAPHY
    text: 'Text',

    // BASIC
    header: 'Header',
    paragraph: 'Paragraph',
    link: 'Link',
    list: 'Simple List',

    // FORMS
    form: 'Form',
    input: 'Input',
    file_input: 'File',
    form_group_input: 'Form Group',
    input_group: 'Input group',
    textarea: 'Textarea',
    select: 'Select',
    select_option: '- Select option -',
    option: 'Option',
    label: 'Label',
    checkbox: 'Checkbox',
    radio: 'Radio',
    trait_method: 'Method',
    trait_enctype: 'Encoding Type',
    trait_multiple: 'Multiple',
    trait_action: 'Action',
    trait_state: 'State',
    trait_id: 'ID',
    trait_for: 'For',
    trait_name: 'Name',
    trait_placeholder: 'Placeholder',
    trait_value: 'Value',
    trait_required: 'Required',
    trait_type: 'Type',
    trait_options: 'Options',
    trait_checked: 'Checked',
    type_text: 'Text',
    type_email: 'Email',
    type_password: 'Password',
    type_number: 'Number',
    type_date: 'Date',
    type_hidden: 'Hidden',
    type_submit: 'Submit',
    type_reset: 'Reset',
    type_button: 'Button',
};
